modernweb-dev/rocket

.changeset/honest-pumas-wink.md, README.md
1. initial release of all `@rocket` packages
=> chore: cut an initial release

.eleventyignore, docs/guides/first-pages/getting-started.md
1. Add override source to `.eleventyignore`
2. Document it for users
=> chore: add info about the need of .eleventyignore

.changeset/wet-waves-wait.md, docs/docs/configuration/overview.md, docs/guides/configuration/getting-started.md, packages/cli/src/RocketStart.js, packages/cli/test-node/RocketCli.e2e.test.js, packages/cli/test-node/e2e-fixtures/content/docs/link.md, packages/cli/test-node/e2e-fixtures/content/pathPrefix.rocket.config.js, packages/eleventy-plugin-mdjs-unified/package.json
1. add pathPrefix option for subfolder deployment
2. will not apply to start command
=> feat: add pathPrefix option for subfolder deployment

.changeset/nervous-peaches-design.md, packages/cli/src/eleventy-plugins/rocketCollections.cjs
- while watching an update should not hide navigation
- makes it definitely more convenient to work with
=> fix(cli): while watching an update should not hide navigation

.changeset/lemon-bulldogs-check.md, packages/cli/src/eleventy-plugins/processLocalReferences.cjs, packages/cli/test-node/RocketCli.e2e.test.js, packages/cli/test-node/e2e-fixtures/image-link/docs/index.md
1. Make sure links to `*index.md` files are not treated as folder index files like `index.md`
=> fix(cli): *index.md should not be treated as folder index files

.changeset/good-mice-act.md, packages/check-html-links/README.md, packages/check-html-links/src/cli.js, packages/check-html-links/src/validateFolder.js
* Add number of files checked
* Add number of links checked
@daKmoR Request for feedback :). Excuse my puny Javascript foo XD
I've also seen that some websites I've tested are somehow stalling. I had to stop the process after 15 minutes. One example is https://github.com/oracle/helidon-site. I'll investigate further.
=> feat: Add some extra info when running html-links

package.json
1. Include `build:package` script to the `setup` script
=> chore: build packages on setup

docs/blog/introducing-check-html-links.md
=> Proposal for changes

.changeset/cold-cobras-swim.md, packages/cli/src/RocketCli.js
1. Watching `_assets`, `_data`, `_includes` for changes to trigger updated automatically
=> fix(cli): watching user preset files to trigger updates automatically

packages/cli/test-helpers/index.js, packages/cli/test-node/RocketCli.computedConfig.test.js, packages/cli/test-node/RocketCli.e2e.test.js, packages/cli/test-node/e2e-fixtures/rollup-plugin/devbuild-build.rocket.config.js
=> chore: use test-helper everywhere

.changeset/witty-snails-help.md, packages/mdjs-preview/src/MdJsPreview.js, packages/mdjs-story/src/MdJsStory.js
1. Pass on the shadowRoot to the story function
=> fix: mdjs element pass on shadowRoot to story function

packages/building-rollup/src/createSpaConfig.js, packages/search/src/RocketSearch.js, packages/search/src/RocketSearchCombobox.js, packages/search/src/RocketSearchOption.js, packages/search/src/utils-shared.js
1. Quite a few of minor and medium level improvements to search functionality as per discussions in https://github.com/modernweb-dev/rocket/issues/41 and https://github.com/daKmoR/rocket/issues/119
=> feat/fix: Search improvements

README.md
1. Fix link to the page with the slack channel
2. Fix a typo I found along the way
=> Tiny fixes to the README

.changeset/beige-rockets-invite.md, packages/cli/src/RocketCli.js, packages/cli/test-node/RocketCli.e2e.test.js
=> feat(cli): make sure each instance has its own eleventy config

.changeset/plenty-parents-cry.md, packages/search/src/RocketSearchCombobox.js
1. Add variable for border-radius of SearchCombobox
=> feat(search): add variable for border-radius of SearchCombobox

.changeset/many-points-eat.md, .changeset/yellow-moose-play.md, docs/docs/markdown-javascript/overview.md, docs/docs/markdown-javascript/preview.md, docs/docs/markdown-javascript/story.md, packages/eleventy-plugin-mdjs-unified/test-node/eleventy-plugin-mdjs-unified.test.js, packages/launch/package.json, packages/mdjs-core/src/mdjsProcess.js, packages/mdjs-core/src/mdjsSetupCode.js, packages/mdjs-core/test-node/mdJsProcess.test.js, packages/mdjs-core/test-node/mdjsParse.test.js, packages/mdjs-core/types/code.d.ts
1. Extract building of the JavaScript setup code into a unified plugin
2. You can provide a highlightCode function to the mdjsSetupCode unified plugin
=> feat(mdjs-core): extract mdjsSetupCode function which support a highlightCode fn

.changeset/sour-ladybugs-beam.md, packages/cli/preset/_includes/layout-simulator.njk, packages/launch/package.json
1.  Pass document shadowRoot to iframe
=> fix(simulator): document shadowRoot n/a in iframe

.changeset/fluffy-glasses-confess.md, .changeset/red-cobras-accept.md, packages/cli/preset/_includes/layout-simulator.njk, packages/mdjs-preview/src/MdJsPreview.js, packages/mdjs-preview/src/mdjsViewerSharedStates.js
1. Do not set `data-localize-lang` in the simulator iframe html tag
2. Make sure initial settings are taken from the element if nothing is yet stored
=> fix(mdjs-preview): initial setting should come from the element

packages/mdjs-core/package.json, packages/mdjs-preview/src/MdJsPreview.js, rocket.config.js
1. Styling: Add color theming palette & add iframe shadow part.
2. No display of simulator > settings > themes & platforms sections, by default.
=> Simulator: New CSS color palette & no default themes & platforms sections

.changeset/beige-taxis-dream.md, .changeset/selfish-horses-search.md, packages/mdjs-preview/src/MdJsPreview.js
1. Improve customizations by hiding empty themes, platforms and adding parts to be styled.
2. Add a copy code button
=> feat(mdjs-preview): improve customisations and add copy button

.changeset/famous-items-dream.md, packages/mdjs-preview/src/MdJsPreview.js
1. Autoheight will not grow bigger than the current size height
=> fix(mdjs-preview): Autoheight will not grow bigger than the current size height

.changeset/many-squids-watch.md, docs/guides/go-live/social-media.md, packages/cli/preset/_includes/_joiningBlocks/head/20-social-media.njk, packages/eleventy-plugin-mdjs-unified/src/eleventy-plugin-mdjs-unified.js, packages/launch/preset/_includes/_joiningBlocks/bottom/10-init-navigation.njk, packages/launch/preset/_includes/_joiningBlocks/head/30-social-media.njk, packages/mdjs-core/src/mdjsSetupCode.js, packages/search/preset/_includes/_joiningBlocks/header/25-search-input.njk
=> fix: support pathprefix in cli, launch, mdjs, search

.changeset/pink-pans-breathe.md, packages/blog/package.json, packages/building-rollup/package.json, packages/cli/package.json, packages/mdjs-core/package.json, packages/search/package.json, yarn.lock
=> fix: support picture tags with <source srset="...">

.changeset/warm-actors-taste.md, packages/eleventy-plugin-mdjs-unified/CHANGELOG.md, packages/eleventy-plugin-mdjs-unified/package.json
=> feat: update to mdjs version with lit 2 and render to light dom

packages/cli/test-helpers/index.js, packages/cli/test-node/RocketCli.e2e.test.js, packages/cli/test-node/RocketCli.images.test.js, packages/cli/test-node/RocketCli.preset.test.js
=> chore: remove image hashes from tests

.changeset/calm-pots-fly.md, packages/cli/src/eleventy-plugins/insertResponsiveImages.cjs, packages/cli/test-node/RocketCli.images.test.js, packages/cli/test-node/e2e-fixtures/images/docs/two-images.md
=> fix(cli): replace images to be responsive from the bottom up

.changeset/rich-ads-sort.md, packages/search/package.json, packages/search/src/RocketSearch.js, packages/search/test-web/rocket-search.test.js, yarn.lock
=> [search] upgrade to lit v2

.changeset/soft-parents-act.md, packages/cli/src/eleventy-plugins/insertResponsiveImages.cjs
=> fix(cli): don't transform external images

.changeset/twenty-paws-decide.md, packages/cli/src/RocketLint.js, packages/cli/types/main.d.ts
1. add `checkLinks` config property
2. forward that to check-links
=> feat(cli): expose checkLinks options

.changeset/thin-brooms-hear.md, docs/docs/configuration/overview.md, docs/guides/presets/options.md, packages/cli/src/RocketCli.js, packages/cli/src/normalizeConfig.js, packages/cli/test-node/normalizeConfig.test.js, packages/cli/types/main.d.ts
1. add `before11ty` hook, which fires before calling `Eleventy#write()`. It awaits all preset's `before11ty` hooks before finally awaiting the user's `before11ty` hook
2. also improved types and fixed a typo
Closes #178
=> feat(cli): add async `before11ty` hook

.changeset/lazy-ligers-swim.md, packages/cli/src/RocketBuild.js, packages/cli/src/eleventy-plugins/rocketCopy.cjs, packages/cli/src/shared/.eleventy.cjs
1. change the glob that copies static assets to a full star
=> fix(cli): copy all static assets on build

.changeset/real-carpets-enjoy.md, packages/launch/preset/_assets/layout.css, packages/launch/preset/_assets/markdown.css, packages/launch/preset/_assets/variables.css
1. Add font-family CSS variables
- `--primary-font-family` for body text
- `--secondary-font-family` for emphasis (e.g. call-to-action)
- `--heading-font-family` for headings (defaults to `--primary-font-family`)
- `--code-font-family` for code blocks
=> feat(launch): move font-family to variables

docs/guides/go-live/overview.md
1. add info that a server needs to handle the 404.html file
closes https://github.com/modernweb-dev/rocket/issues/102
=> docs: add info that a server needs to handle the 404.html file

packages/launch/preset/_includes/_joiningBlocks/header/30-collection-header.njk
fixes #189
1. check for existence of page.url.search before calling it
a better solution would abstract that call to something in the search preset
=>  Update 30-collection-header.njk

docs/guides/configuration/getting-started.md
=> chore: improve wording in getting-started.md

.changeset/tough-fireants-protect.md, packages/launch/preset/_data/footer.json
=> fix(launch): remove footer extra comma

docs/docs/tools/check-html-links.md
1. Fix inline-notification script import
=> Fix inline-notification script import

docs/guides/first-pages/getting-started.md
1. Fixed a tiny typo from `doc/index.md` to `docs/index.md`
=> docs: change doc to docs

.changeset/chatty-poems-cover.md, package.json, packages/blog/package.json, packages/plugins-manager/index.js, packages/plugins-manager/types/main.d.ts, packages/search/package.json, yarn.lock
1. fix dist-types for plugin-manager
=> fix(plugins-manager): dist types

.changeset/pretty-toys-prove.md, packages/blog/package.json, packages/cli/package.json, packages/mdjs-core/package.json, packages/search/package.json
1. update plugins-manager version in various packages
=> chore: update dependencies

.changeset/violet-guests-try.md, packages/cli/src/eleventy-plugins/insertResponsiveImages.cjs, packages/cli/test-node/RocketCli.images.test.js, packages/cli/test-node/e2e-fixtures/images/docs/table.md
=> fix(cli): use openEnd to insert responsive image

.changeset/popular-knives-bathe.md, packages/blog/preset/_assets/rocket-blog.css, packages/blog/preset/_includes/_joiningBlocks/_layoutBlogOverview/content/30-articles.njk
alignment + spacings for article grids:
- thumbnail heights always align
- no spacing between border-bottom of thumbnail and image
- appropriate top padding for h2
- top alignment in grid instead of middle alignment between articles
=> fix(blog): alignment + spacings for article grids

.changeset/forty-bananas-ring.md, .changeset/slow-meals-own.md, docs/_assets/theme.css, packages/launch/preset/_assets/variables.css, packages/mdjs-preview/src/MdJsPreview.js
1. Fix styling in darkmode
2. Make [slot="content"] selector more specific
=> fix(mdjs-viewer): fix styling mdjs-viewer

docs/guides/go-live/overview.md
1. exclude 404 page from sitemap
=> fix: hide 404 page from sitemap.xml

.changeset/fuzzy-seahorses-roll.md, packages/blog/preset/_includes/_joiningBlocks/_layoutBlogDetails/content/10-title.njk
=> fix(blog): add title to blog page

packages/blog/preset/_includes/_joiningBlocks/_layoutBlogOverview/content/30-articles.njk, packages/blog/preset/_includes/_joiningBlocks/head/add-blog-css.njk
1. change thumbnails background property to background-image
2. applied css to center and cover the image
=> fix(blog): fix blog overview thumbnail styles

packages/mdjs-core/package.json, packages/mdjs-core/test-node/integration.test.js, packages/mdjs-core/test-node/mdjsParse.test.js, packages/mdjs-core/test-node/mdjsStoryParse.test.js, yarn.lock
1. chore: update remark-html
2. chore: lock file maintenance
=> Security updates in lock file

.changeset/strange-houses-protect.md, packages/mdjs-preview/src/MdJsPreview.js
=> fix(mdjs-preview): add css variable to border-color of viewer

.changeset/sweet-countries-shave.md, packages/mdjs-core/package.json
=> fix(mdjs-core): add missing slash dependency

package.json, yarn.lock
=> chore: lock file maintenance

.changeset/odd-pumpkins-rhyme.md, docs/docs/tools/plugins-manager.md, packages/plugins-manager/src/addPlugin.js, packages/plugins-manager/test-node/addPlugin.test.js
=> feat(plugins-manager): support a wrapPlugin property for adding

.changeset/popular-llamas-fly.md, packages/cli/src/eleventy-plugins/insertResponsiveImages.cjs, packages/eleventy-rocket-nav/src/addPageAnchors.js
=> fix: improve performance by loading sax-wasm only once

.changeset/dry-dots-drop.md, packages/search/package.json, yarn.lock
=> feat(rocket-search): update lion dependencies

packages/launch/src/LayoutSidebar.js, site/pages/10--docs/10--setup/10--getting-started.rocket.md, site/pages/10--docs/20--basics/10--project-structure.rocket.md, site/pages/10--docs/20--basics/20--pages.rocket.md, site/pages/10--docs/20--basics/70--navigation.rocket.md, site/pages/10--docs/30--guides/50--go-live.rocket.md, site/pages/10--docs/30--guides/90--data-fetching.rocket.md, site/pages/10--docs/30--guides/95--deploy.rocket.md, site/pages/pageTreeData.rocketGenerated.json
- Fix the "edit this page on GitHub" link
- Fix internal links on Getting Started page
- Fix internal links on Project Structure page
=> Bugfix: Fix broken link

README.md
=> chore: change URLs to use next in main README.md

.changeset/fifty-bats-report.md, README.md, packages/mdjs-preview/package.json
1. fix(mdjs-preview): add server folder to the published npm package
2. chore: in readme use us images from main branch
=> fix(mdjs-preview): add server folder to the published npm package

.changeset/tall-onions-sort.md, packages/building-rollup/src/createBasicConfig.js, packages/building-rollup/src/createServiceWorkerConfig.js, packages/cli/tsconfig.json, packages/engine/src/dev-server/devServerAdjustAssetUrls.js, packages/engine/src/formats/markdown.js, packages/engine/test-node/14c-components-e2e.spec.js, packages/engine/tsconfig.json, packages/launch/tsconfig.json, packages/search/tsconfig.json, site/pages/pageTreeData.rocketGenerated.json, tsconfig.json, workspace-packages.mjs, yarn.lock
- chore: refresh lock file
- fix(building-rollup): apply user provided developmentMode
=> chore: refresh lock file

.changeset/chilly-ties-repair.md, packages/engine/src/Engine.js, packages/engine/test-node/10-plugins.test.js, packages/engine/test-node/fixtures/10-plugins/02-input-folder-public-always-wins/docs/index.rocket.js, packages/engine/test-node/fixtures/10-plugins/02-input-folder-public-always-wins/docs/pageTreeData.rocketGenerated.json, packages/engine/test-node/fixtures/10-plugins/02-input-folder-public-always-wins/plugin-add-to-public/preset/__public/added-via-plugin-and-input-public.txt, packages/engine/test-node/fixtures/10-plugins/02-input-folder-public-always-wins/public/added-via-plugin-and-input-public.txt, packages/search/test-web/rocket-search.test.js
1. Implement and add test for it
fixes https://github.com/modernweb-dev/rocket/issues/393
=> fix(engine): make sure inputDir public folder wins over plugins public folders

.changeset/funny-seals-run.md, examples/01-hydration-starter/package.json, examples/02-blog-starter/package.json, examples/03-minimal-starter/package.json, examples/04-sanity-minimal-starter/frontend/package.json, examples/50-landing-theme-spark/package.json, examples/51-docs-theme-launch/package.json, packages/components/package.json, packages/engine/package.json, packages/engine/src/formats/markdown.js, packages/engine/src/index.js, packages/engine/src/worker/importWorker.js, packages/engine/src/worker/renderWorker.js, packages/engine/test-node/04a-renderJoiningGroup.test.js, packages/launch/package.json, packages/mdjs-preview/package.json, packages/mdjs-story/package.json, presets/spark/package.json, yarn.lock
=> feat(engine): remove global dom shim workaround

.changeset/bright-emus-design.md, packages/cli/package.json, packages/cli/src/RocketBuild.js, packages/cli/src/RocketCli.js, packages/cli/src/RocketLint.js, packages/cli/src/build/buildHtml.js, packages/cli/src/build/buildJavaScriptOptimizedOutput.js, packages/cli/src/build/buildOpenGraphImages.js, packages/cli/types/main.d.ts, site/pages/10--docs/30--guides/50--go-live.rocket.md, site/pages/pageTreeData.rocketGenerated.json, yarn.lock
1. Introducing `rocket lint` to verify if all your links are correct.
There are two modes:
```bash
rocket lint
rocket lint --build-html
```
=> feat(cli): introduce "rocket lint"

site/pages/10--docs/10--setup/10--getting-started.rocket.md, site/pages/10--docs/10--setup/20--adding-pages.rocket.md, site/pages/10--docs/20--basics/10--project-structure.rocket.md, site/pages/10--docs/20--basics/20--pages.rocket.md, site/pages/10--docs/20--basics/30--data-cascade.rocket.md, site/pages/10--docs/20--basics/40--components.rocket.md, site/pages/10--docs/20--basics/50--layouts.rocket.md, site/pages/10--docs/20--basics/60--routing.rocket.md, site/pages/10--docs/20--basics/70--navigation.rocket.md, site/pages/10--docs/20--basics/80--hydration.rocket.md, site/pages/10--docs/20--basics/90--assets.rocket.md, site/pages/10--docs/20--basics/95--configuration.rocket.md, site/pages/10--docs/30--guides/20--social-media.rocket.md, site/pages/10--docs/30--guides/30--images.rocket.md, site/pages/10--docs/30--guides/80--web-fonts.rocket.md, site/pages/20--presets/20--launch/10--overview.rocket.md, site/pages/20--presets/20--launch/20--service-worker.rocket.md
Remove extraneous words and correct misphrasings.
=> docs: site cleanup

.vscode/settings.json, package-lock.json, package.json, packages/engine/src/Engine.js, packages/mdjs-core/src/mdjsProcess.js
=> chore: update to typescript 4.8.4
