modernweb-dev/rocket

- .changeset/fair-bugs-destroy.md
- .changeset/fair-worms-type.md
- docs/docs/configuration/overview.md
- docs/docs/tools/plugins-manager.md
- packages/cli/src/RocketBuild.js
- packages/cli/src/RocketStart.js
- packages/cli/test-node/RocketCli.e2e.test.js
- packages/plugins-manager/src/metaConfigToRollupConfig.js
- packages/plugins-manager/src/metaConfigToWebDevServerConfig.js
- packages/plugins-manager/test-node/metaConfigToRollupConfig.test.js
- packages/plugins-manager/test-node/metaConfigToWebDevServerConfig.test.js
- packages/plugins-manager/types/main.d.ts
- Do not auto rollupWrap plugins added via `setupDevPlugins`.
- If you provide `devServer.plugins` then it will return that directly ignoring `setupDevAndBuildPlugins` and `setupDevPlugins`
> fix: only apply the rollup wrap of dev server plugins if needed

- .changeset/afraid-apricots-burn.md
- .changeset/silent-coins-suffer.md
- .changeset/strange-years-wave.md
- packages/building-rollup/package.json
- packages/cli/src/RocketBuild.js
- packages/cli/src/RocketCli.js
- packages/cli/test-node/RocketCli.e2e.test.js
- packages/cli/test-node/e2e-fixtures/content/docs/_assets/some.css
- packages/cli/test-node/e2e-fixtures/content/docs/use-assets.md
- packages/launch/preset/_includes/partials/head-content.njk
- yarn.lock
1. Make sure assets can still be found for building when using `pathPrefix`
Depends on a new release of rollup-plugin-html with https://github.com/modernweb-dev/web/pull/1179 included
> fix(cli): rollup-plugin-html needs to be aware of the pathPrefix

- .changeset/rude-seals-compete.md
- packages/launch/inline-notification/index.js
1. add css vars to inline-notifications
- `--inline-notification-danger-background-color`
- `--inline-notification-danger-border-color`
- `--inline-notification-danger-heading-color`
- `--inline-notification-tip-background-color`
- `--inline-notification-tip-border-color`
- `--inline-notification-warning-background-color`
- `--inline-notification-warning-border-color`
- `--inline-notification-warning-heading-color`
> feat(launch): themability for inline-notification

- .changeset/nice-plants-prove.md
- .changeset/olive-turkeys-complain.md
- .changeset/small-chicken-type.md
- package.json
- packages/cli/src/normalizeConfig.js
- packages/cli/src/public/rocketEleventyComputed.cjs
- packages/cli/test-node/RocketCli.e2e.test.js
- packages/launch/preset/_assets/logo.svg
- packages/mdjs-core/package.json
- packages/mdjs-core/src/mdjsProcess.js
- packages/mdjs-core/test-node/mdJsProcess.test.js
- yarn.lock
1. Add gfm to support markdown tables
2. Make default logo work with auto generating social media images
3. Better support for windows paths
closes: https://github.com/modernweb-dev/rocket/issues/24
> Markdown table and windows support

- .changeset/curly-poets-hunt.md
- packages/check-html-links/src/validateFolder.js
1. Increase highWaterMark
2. sync highWaterMark between reading stream and parsing stream
closes https://github.com/modernweb-dev/rocket/issues/48
> fix(check-html-links): read and parse with the same increased highWaterMark

- packages/check-html-links/package.json
- packages/check-html-links/src/CheckHtmlLinksCli.js
- packages/check-html-links/src/cli.js
- packages/check-html-links/src/validateFolder.js
- packages/check-html-links/test-node/fixtures/external-link/index.html
- packages/check-html-links/test-node/test-helpers.js
- packages/check-html-links/test-node/validateFolder.test.js
- packages/check-html-links/types/main.d.ts
1. Add a `--ignore-link-pattern` option to the CLI
2. Add a `--dir` option  to the CLI
The following commands are equivalent:
```
$ npx check-html-links _site
```
```
$ npx check-html-links --dir _site
```
3. Introduce a options object to the `validateFolder` and `validateFiles` functions
4. Convert link patterns (glob syntax) to regular expressions using `minimatch`
5. Pass a `ignoreUsage` function to the `resolveLinks` function to decide if a usage should be ignored or not
If we want to offer more flexibility, the `ignoreUsage` function (`function(Usage): boolean`) could be defined by the user.
> resolves #54 introduce a ignoreLinkPatterns option

- .changeset/nice-parrots-punch.md
- .changeset/pink-melons-matter.md
- docs/docs/tools/check-html-links.md
- packages/check-html-links/index.js
- packages/check-html-links/src/CheckHtmlLinksCli.js
- packages/check-html-links/src/validateFolder.js
- packages/check-html-links/test-node/fixtures/internal-link-ignore/index.html
- packages/check-html-links/test-node/validateFolder.test.js
- packages/check-html-links/types/main.d.ts
- packages/cli/package.json
- packages/cli/src/RocketLint.js
1. Rocket: Use class based node api of check-html-links
2. Release of ignore links pattern & add continueOnError
> fix: use class node api of check-html-links in rocket

- packages/drawer/src/RocketDrawer.js
> Rebase of https://github.com/modernweb-dev/rocket/pull/76
1. Added possibility to declare a custom media query for the `useOverlay` switch in RocketDrawer.
2. Switched from a [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#methods) addListener method to addEventListener
```js
<rocket-drawer useOverlayMediaQuery="(max-width: 768px)">
```
> feat: Allow overlay query modification in Drawer (#73)

- .changeset/tasty-baboons-argue.md
- packages/eleventy-rocket-nav/.eleventy.js
- packages/eleventy-rocket-nav/eleventy-rocket-nav.js
- packages/eleventy-rocket-nav/package.json
- packages/eleventy-rocket-nav/src/addPageAnchors.js
- packages/eleventy-rocket-nav/test-node/addPageAnchors.test.js
- packages/eleventy-rocket-nav/test-node/fixtures/three-pages/.eleventy.js
- packages/eleventy-rocket-nav/test-node/fixtures/three-pages/_data/layout.cjs
- packages/eleventy-rocket-nav/test-node/fixtures/three-pages/_includes/layout.njk
- packages/eleventy-rocket-nav/test-node/fixtures/three-pages/bats.md
- packages/eleventy-rocket-nav/test-node/fixtures/three-pages/humans.md
- packages/eleventy-rocket-nav/test-node/fixtures/three-pages/mammals.md
- packages/eleventy-rocket-nav/test-node/integration.test.js
1. To support dynamically created content to be part of the anchor navigation of the page we now analyze the final html output instead of `entry.templateContent`.
BREAKING CHANGE:
- only add anchors for the currently active pages (before it added anchor for every page)
closes: https://github.com/modernweb-dev/rocket/issues/42
> feat(eleventy-rocket-nav): support dynamically created content

- .changeset/hip-eels-remain.md
- packages/building-rollup/package.json
- packages/check-html-links/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/mdjs-preview/package.json
- packages/mdjs-story/package.json
- packages/plugins-manager/package.json
- packages/search/package.json
This allows the tools to work properly. For example, eslint-plugin-import, TypeScript LSP hyperclick, and many other tools rely on main.
1. add missing main entry to the packages
> fix: add missing main entry to the packages

- .changeset/nasty-hats-smash.md
- docs/guides/first-pages/manage-sidebar.md
- packages/navigation/src/RocketNavigation.js
- packages/navigation/test-web/rocket-navigation.test.js
By default, the sidebar nav redirects clicks on category headings to
their first child.
To disable those redirects, override
`_includes/_joiningBlocks/_layoutSidebar/sidebar/20-navigation.njk`
and add the `no-redirects` attribute to the `<rocket-navigation>`
element.
1. check for `no-redirects` attribute before preventing default click handler and redirecting
2. debounce scroll spy
3. fix a test which was failing when it expected an anchor and got a list item
4. adjust tests to handle debounced scroll listener
> feat(navigation): add no-redirects attribute

- .changeset/chilled-turkeys-help.md
- packages/search/src/RocketSearch.js
- packages/search/src/RocketSearchOption.js
1. Generalized rocket search label, so it works for all extending parties
2. Added alt attribute to images search results for a11y
> chore: generalize label & add alt when no img

- .changeset/thirty-turkeys-own.md
- packages/cli/package.json
- packages/cli/src/eleventy-plugins/rocketCollections.cjs
1. Fix an issue on windows because of the path with backslashes.
On windows, the /blog uses the blog detail layout and display a wrong navigation sidebar:
> fix: windows path issue avoid filtering of index section of collections

- .changeset/silent-hairs-cheat.md
- packages/check-html-links/src/validateFolder.js
1. fix `rocket lint` with windows path
I didn't check the lint feature when I fixed it for the `rocket start` in https://github.com/modernweb-dev/rocket/pull/104
> fix: windows path issue when using rocket lint

- .changeset/good-ears-move.md
- packages/mdjs-core/package.json
1. fix(mdjs-core): support importing via es module
> fix(mdjs-core): support importing via es module

- .changeset/fresh-files-deny.md
- package.json
- packages/eleventy-plugin-mdjs-unified/package.json
- yarn.lock
1. Bumping tsc version so it respects jsdoc optional parameters when generating typings
> fix(plugins-manager): fix types for optional parameters

- .changeset/core-light-dom.md
- .changeset/core.md
- .changeset/dirty-vans-brush.md
- .changeset/light-dom-story.md
- .changeset/mighty-grapes-build.md
- .changeset/story.md
- docs/docs/markdown-javascript/overview.md
- docs/docs/markdown-javascript/preview.md
- docs/docs/markdown-javascript/story.md
- package.json
- packages/cli/preset/_includes/layout-simulator.njk
- packages/mdjs-preview/index.js
- packages/mdjs-preview/package.json
- packages/mdjs-preview/src/MdJsPreview.js
- packages/mdjs-preview/test-web/mdjs-preview.test.js
- packages/mdjs-story/index.js
- packages/mdjs-story/package.json
- packages/mdjs-story/src/MdJsStory.js
- packages/mdjs-story/test-web/mdjs-story.test.js
- yarn.lock
1. @mdjs/mdjs-preview, @mdjs/mdjs-story
**BREAKING CHANGE** Update to [lit](https://lit.dev/) 2
If your main lit-html version is 1.x be sure to import html for your story rendering from `@mdjs/mdjs-preview`.
````md
```js script
import { html } from '@mdjs/mdjs-preview';
```
```js preview-story
export const foo = () => html`<demo-element></demo-element>`;
```
````
2. @mdjs/mdjs-preview, @mdjs/mdjs-story
**BREAKING CHANGE** Render stories to light dom
```js
export const story = html`<p>my story</p>`;
```
```html
<mdjs-story>
#shadow-root (open)
<p>my story</p>
</mdjs-story>
<mdjs-story>
<p>my story</p>
</mdjs-story>
```
3. @mdjs/core
**BREAKING CHANGE** by updating dependencies
> feat: update mdjs to lit & render to light dom

- .changeset/mighty-books-guess.md
- docs/_includes/_joiningBlocks/head/site.njk
- packages/launch/preset/_includes/_joiningBlocks/head/40-stylesheets-fonts.njk
1. Load Open Sans and Monserrat from google fonts.
2. Add preconnect lint to reduce time to load fonts
3. Load fonts with `display: optional` as recommend post added on #36
4. Remove fonts from docs/_includes/*/site.njk
Fix #36
> feat(launch): load used fonts from google fonts

- .changeset/mean-mangos-clap.md
- packages/launch/preset/_data/footer.json
1. Remove footer urls to pages that users would need to create
closes https://github.com/modernweb-dev/rocket/issues/188
closes https://github.com/modernweb-dev/rocket/issues/124
> fix(launch): remove footer urls that require user creation

- .changeset/early-pots-guess.md
- packages/launch/preset/_includes/partials/mobile-sidebar-bottom.njk
1. Only show the help & feedback link if a site.helpUrl is defined
closes https://github.com/modernweb-dev/rocket/issues/103
> fix(launch): create help & feedback link only if site.helpUrl is defined

- .changeset/healthy-oranges-shake.md
- packages/mdjs-preview/package.json
- packages/mdjs-preview/src/MdJsPreview.js
- yarn.lock
1. Get a scoped registry for the internal accordion element to no longer pollute the global registry with a `lion-accordion` element.
> fix(mdjs-preview): use a scoped registry for the internal accordion element

- scripts/lint-versions.js
1. Fix version number of internal packages
When an internal package is updated dependant packages are not updated. Fixing version number instead of using `^` allows changeset to update versions of related packages, and publish all changed packages and their dependants.
Actually, every version update breaks all PR because of the version linter. With this will be aligned all version on each publish
> fix: use semver to lint versions

- .changeset/shiny-swans-drop.md
- packages/cli/preset/_includes/layout-simulator.njk
1. Set the encoding of the simulator to utf8 via a html meta tag
> fix(cli): set the encoding of the simulator to utf8

- .changeset/lazy-nails-itch.md
- packages/cli/preset/_includes/_joiningBlocks/bottom/180-register-service-worker.njk
- packages/cli/test-node/RocketCli.preset.test.js
- packages/cli/test-node/RocketCli.service-worker.test.js
- packages/launch/test-node/RocketLaunch.preset.test.js
Since you don't need it when updating a website, it's simpler to disable it by default.
> fix: disable service worker for local development

- .changeset/strange-clouds-grab.md
- .changeset/strange-clouds-grab2.md
- netlify.toml
- packages/cli/preset/_includes/layout-simulator.njk
- packages/mdjs-preview/src/MdJsPreview.js
1. Enable including script files into the simulator via `<script src=".." mdjs-use>`
2. Allow only a limited set of characters for simulator includes `[a-zA-Z0-9\/\-_]`.
Notably, there is no:
- `:` to prevent `http://...` includes
- `.` so filenames as `this.is.my.js` are not supported. Also includes will be without file endings which will be added automatically
> fix: improve mdjs preview iframe security

- .changeset/purple-meals-count.md
- packages/mdjs-preview/src/MdJsPreview.js
- packages/mdjs-preview/src/mdjsViewerSharedStates.js
In our Design System we style each component based on `theme="light/dark"`, also the `mdjs-preview`.
If we changed  of the theme via the viewer that not only the preview section switched theme but the full `mdjs-preview`.
See image below:
This PR separates the theme set on the preview from the viewer itself.
> fix(mdjs-preview): separate preview and viewer theme styling

- .changeset/rare-toys-battle.md
- packages/drawer/package.json
1. Add export map which enables side effect import via `@rocket/drawer/define`
> fix(drawer): add export map with /define side effect import

- .changeset/plenty-trainers-taste.md
- CONTRIBUTING.md
- docs/blog/introducing-check-html-links.md
- docs/docs/eleventy-plugins/mdjs-unified.md
- docs/docs/tools/check-html-links.md
- docs/guides/first-pages/manage-sidebar.md
- packages/check-html-links/README.md
- packages/mdjs-core/package.json
- packages/mdjs-core/src/mdjsProcess.js
- packages/mdjs-core/test-node/mdJsProcess.test.js
- packages/mdjs-core/types/remark.d.ts
- packages/mdjs-preview/package.json
- yarn.lock
1. Use `rehype-prism-plus` instead of `rehype-prism-template` so that `prismjs` can resolve to the latest version and reduce vulnerability alerts in down stream projects.
> Use a more recently published prism converter for rehype

- .changeset/four-pets-brush.md
- packages/mdjs-core/src/mdjsParse.js
- packages/mdjs-core/test-node/mdjsParse.test.js
> feat(mdjs-core): support `js client` as an alias to `js script`

- site/pages/10--docs/20--basics/90--assets.rocket.md
- site/pages/10--docs/30--guides/70--styles-and-css.rocket.md
- site/pages/pageTreeData.rocketGenerated.json
- Just a couple of typo fixes
- Started the Styles And CSS Guide
> [next] Doc Updates

- .changeset/tiny-ties-press.md
- .gitignore
- docs/docs/markdown-javascript/preview.md
- package.json
- packages/drawer/src/RocketDrawer.js
- packages/mdjs-preview/src/MdJsPreview.js
- packages/mdjs-preview/test-web/mdjs-preview.subclasser.test.js
- packages/mdjs-preview/test-web/mdjs-preview.test.js
- yarn.lock
It is possible to define a custom version of mdjs-preview in order to add functionality, change
its appearance of make it run in 'hybrid mode' (accepting both lit1 and -2 TemplateResults).
The example below shows how the latter can be achieved by providing a custom render function.
Note that we define `mdjs-preview` as the custom element name. We need to make sure that this
file is executed before the original mdjs-preview definition file is executed.
```js
import { MdJsPreview } from '@mdjs/mdjs-preview';
import { render as render2 } from 'lit';
import { isTemplateResult as isTemplateResult2 } from 'lit/directive-helpers.js';
import { render as render1  } from 'lit-html';
export class HybridLitMdjsPreview extends MdJsPreview {
get renderFunction() {
return function renderHybrid(html, …
```
> feat(mdjs-preview): provide overridable `renderFunction`

- docs/guides/index.md
> docs: fix typo in guides index

- .changeset/early-shrimps-applaud.md
- packages/engine/src/Engine.js
- packages/engine/src/Watcher.js
- packages/engine/test-node/09b-watch-error-handling.test.js
- packages/engine/test-node/fixtures/09b-watch-error-handling/04-update-header-while-rendering/components/HelloTyper.js
- packages/engine/test-node/fixtures/09b-watch-error-handling/04-update-header-while-rendering/docs/index.rocket.js
- packages/engine/test-node/fixtures/09b-watch-error-handling/04-update-header-while-rendering/docs/pageTreeData.rocketGenerated.json
- packages/engine/test-node/fixtures/09b-watch-error-handling/04-update-header-while-rendering/docs/recursive.data.js
- packages/engine/test-node/fixtures/09b-watch-error-handling/04-update-header-while-rendering/package.json
1. Prevent fatal error because of simultaneous write to file.
When the browser requested a file to be rendered and that file also needed an update in the "rocket header" (the top of the file) then it could be that the watcher trigger a simultaneous render of the file while the first render was still in progress.
The solution is that the watcher ignores changes to a file until a full render is finished.
fixes https://github.com/modernweb-dev/rocket/issues/375
> fix(engine): prevent fatal error because of simultaneous write to file

- .changeset/many-pigs-admire.md
- .changeset/silly-islands-sparkle.md
- packages/engine/src/web-menu/getHtmlMetaData.js
- packages/engine/src/web-menu/sax-parser.js
- packages/engine/test-node/05z-menu.test.js
- packages/engine/test-node/09b-watch-error-handling.test.js
- packages/engine/test-node/fixtures/04-layouts/01-function/docs/pageTreeData.rocketGenerated.json
- packages/engine/test-node/fixtures/05-menu/14-get-all-text-but-strip-html/docs/index.rocket.js
- packages/engine/test-node/fixtures/05-menu/14-get-all-text-but-strip-html/docs/pageTreeData.rocketGenerated.json
- packages/engine/test-node/fixtures/05-menu/14-get-all-text-but-strip-html/docs/recursive.data.js
- packages/engine/test-node/fixtures/05-menu/15-md-special-characters/docs/component.rocket.md
- packages/engine/test-node/fixtures/05-menu/15-md-special-characters/docs/index.rocket.md
- packages/engine/test-node/fixtures/05-menu/15-md-special-characters/docs/pageTreeData.rocketGenerated.json
- packages/engine/test-node/fixtures/05-menu/15-md-special-characters/docs/recursive.data.js
- packages/engine/test-node/fixtures/05-menu/16-link-text-attribute/docs/index.rocket.js
- packages/engine/test-node/fixtures/05-menu/16-link-text-attribute/docs/pageTreeData.rocketGenerated.json
- packages/engine/test-node/fixtures/05-menu/16-link-text-attribute/docs/recursive.data.js
- site/pages/10--docs/20--basics/70--navigation.rocket.md
1. Make sure the most common use cases for menu renaming are supported
closes https://github.com/modernweb-dev/rocket/issues/236
> feat: improve menu parsing to enable html and renaming

- site/pages/10--docs/10--setup/10--getting-started.rocket.md
1. Corrected the path of the examples link.
> docs: correct path of examples link.

- .changeset/kind-bats-occur.md
- .changeset/thirty-scissors-jam.md
- package.json
- packages/cli/package.json
- packages/cli/src/RocketStart.js
- packages/cli/src/start/logStartMessage.js
- packages/cli/test-helpers/index.js
- packages/cli/test-helpers/test-helpers.js
- packages/cli/test-node/01-config.test.js
- packages/cli/test-node/02-build.test.js
- packages/cli/test-node/03-upgrade.test.js
- packages/cli/test-node/04-open-graph.test.js
- packages/cli/test-node/05-start.test.js
- packages/cli/test-node/fixtures/05-start/01-start-message/site/pages/index.rocket.js
- packages/cli/test-node/fixtures/05-start/01-start-message/site/pages/pageTreeData.rocketGenerated.json
- packages/engine/package.json
- packages/engine/src/Engine.js
- packages/search/test-node/rocket.test.js
- yarn.lock
1. Add start message for `rocket start`
```
🚀 Rocket Engine v0.2.5
🚧 Local:    http://localhost:8000/
🌐 Network:  http://xxx.xxx.xxx.xxx:8000/
```
closes https://github.com/modernweb-dev/rocket/issues/410
> feat(cli): add start message with local and network url

- .changeset/fluffy-impalas-mix.md
- packages/engine/src/transformers/AdjustAssetUrls.js
- packages/engine/test-node/08a-AdjustAssetUrls.test.js
- packages/engine/test-node/test-helpers.js
- site/pages/30--tools/30--rollup-config/10--overview.rocket.md
1. Adjust urls containing url fragments
```html
<a href="./about.rocket.js#some-id"></a>
<a href="./about.rocket.js#some-id"></a>
<a href="/about/#some-id"></a>
```
> fix(engine): support fragments when adjusting urls

- .changeset/real-moose-check.md
- package-lock.json
- packages/building-rollup/package.json
1. Updated the `@babel/core` library in `building-rollup` package to resolve the recent `json5` security vulnerability. 
This updated `@babel/core` from 17.19.6 to 17.20.12. Changes to that library are minor and can be reviewed in their [commit history](https://github.com/babel/babel/commits/main?before=c19d2f60d4e4c70f287eab10e3688e58a0d76d56+35&branch=main&path%5B%5D=packages&path%5B%5D=babel-core&qualified_name=refs%2Fheads%2Fmain). 
Ran tests successfully in `packages/building-rollup`.
> fix(building-rollup): resolve json5 security vulnerability
